### ISSUE TITLE
"Unable to find Geographical annotation"

### ISSUE THREAD

**Issue by stoefln** [dustin10/VichGeographicalBundle#13]
as i already lined out on IRC, there is some problem with loading the annotation from the class. weird thing is: the venue entity long and lat coordinates get inserted correctly, but rendering the map throws this error.
this error occures at MapHelper.php at line 162:

<pre>
        $annot = $this->driver->getGeographicalAnnotation($obj);
        if (null === $annot) {
            throw new \InvalidArgumentException('Unable to find Geographical annotation');
        }
</pre>

as I believe this is related to some reflection or proxy issue...

**Comment by dustin10** [comment]
I have pushed a fix for this that will work for now. I am going to open another issue to fix this issue in a more elegant way.

**Comment by stoefln** [comment]
great- thanks for investigating!

**Comment by stoefln** [comment]
and - forgot to say: works like a charm!
