### ISSUE TITLE
"Unable to find GeograhicalQuery annotation."

### ISSUE THREAD

**Issue by ghost** [dustin10/VichGeographicalBundle#17]
I just add the bundle to my project and I have the following class : 

use Vich\GeographicalBundle\Annotation as Vich;

/**
 *
- @ORM\Entity() 
- @Vich\Geographical(on="update")
  */
  class Contact
  {
  
   /**Some variables */
  
  /**
  - @ORM\Column(type="decimal", scale="7")
    */
    protected $latitude;
  
  /**
  - @ORM\Column(type="decimal", scale="7")
    */
    protected $longitude;
  
  /**
  - @Vich\GeographicalQuery
    *
    _/  
    public function getAdress()
      {
          return sprintf(
              '%s, %s, %s %s',
              $this->rue,
              $this->ville,
              $this->pays,
              $this->cp
          );
      } 
    /_*Some methods */
    }

No special configuration. 

When the object is updated I have the following error : 

"Unable to find GeograhicalQuery annotation. "

Im not sure if I forgot something or if it's a problem with the bundle. 

Thanks a lot for your work !

**Comment by dustin10** [comment]
I'm on Thanksgiving vacation so can't really get in front of my laptop right now. No one else has had an issue like this that I know of. Can you give more detail please. When is this happening? When creating? Updating? Viewing in a map?

**Comment by dustin10** [comment]
Any updates on this?

**Comment by vizo** [comment]
I have the same issue ...

**Comment by dustin10** [comment]
Can you please expand more on when this is happening? Thanks.

**Comment by vizo** [comment]
WIth AdminBundle it's updated without problems ... But when i'm trying to update it from client side.. it throws this...

Stack Trace
in /home/vivizio/workspace/airotours.com/vendor/bundles/Vich/GeographicalBundle/EventListener/GeographicalListener.php at line 110  
        }

```
    if (null === $geoQuery) {
        throw new \InvalidArgumentException('Unable to find GeograhicalQuery annotation.');
    }

    $queryMethod = $geoQuery->getMethod();
```

at GeographicalListener ->updateObject (object(AirotoursApplicationBundleEntityAirportProxy), object(Geographical), null, true, object(PreUpdateEventArgs)) 
in /home/vivizio/workspace/airotours.com/vendor/bundles/Vich/GeographicalBundle/EventListener/GeographicalListener.php at line 90  
at GeographicalListener ->preUpdate (object(PreUpdateEventArgs)) 
in /home/vivizio/workspace/airotours.com/vendor/doctrine-common/lib/Doctrine/Common/EventManager.php at line 64  
at EventManager ->dispatchEvent ('preUpdate', object(PreUpdateEventArgs)) 
in /home/vivizio/workspace/airotours.com/vendor/doctrine/lib/Doctrine/ORM/UnitOfWork.php at line 761  
at UnitOfWork ->executeUpdates (object(ClassMetadata)) 
in /home/vivizio/workspace/airotours.com/vendor/doctrine/lib/Doctrine/ORM/UnitOfWork.php at line 293  
at UnitOfWork ->commit () 
in /home/vivizio/workspace/airotours.com/vendor/doctrine/lib/Doctrine/ORM/EntityManager.php at line 334  
at EntityManager ->flush () 
in /home/vivizio/workspace/airotours.com/src/Airotours/UtilsBundle/Controller/LastMinuteController.php at line 83  
at LastMinuteController ->updateAirport ('35') 
in /home/vivizio/workspace/airotours.com/src/Airotours/UtilsBundle/Controller/LastMinuteController.php at line 57  
at LastMinuteController ->updateAction () 
at call_user_func_array (array(object(LastMinuteController), 'updateAction'), array()) 
in kernel.root_dir/cache/dev/classes.php at line 3883  
at HttpKernel ->handleRaw (object(Request), '1') 
in kernel.root_dir/cache/dev/classes.php at line 3853  
at HttpKernel ->handle (object(Request), '1', true) 
in kernel.root_dir/cache/dev/classes.php at line 4830  
at HttpKernel ->handle (object(Request), '1', true) 
in kernel.root_dir/bootstrap.php.cache at line 547  
at Kernel ->handle (object(Request)) 
in /home/vivizio/workspace/airotours.com/web/app_dev.php at line 20

If you need any more information just ask :)

**Comment by dustin10** [comment]
Ok I just pushed what I think may fix this. Please update and try again.

**Comment by vizo** [comment]
thanks :)

**Comment by dustin10** [comment]
@vivizio Is it working for you now?

**Comment by vizo** [comment]
Yes it looks like it works! :) Thanks!

**Comment by dustin10** [comment]
Ok closing for now. @michmichant please reopen if you still have the issue after updating.
