### ISSUE TITLE
Leaflet support

### ISSUE THREAD

**Issue by snc** [dustin10/VichGeographicalBundle#2]
It would be nice to add support for [Leaflet](http://leaflet.cloudmade.com/examples/quick-start.html). What do you think? I could provide a PR.

**Comment by dustin10** [comment]
I finished abstracting out the rendering of the javascripts and stylesheets to the map renderer object. A PR for this should be easy now. I may also need to look into modifying the Map class.

**Comment by dustin10** [comment]
Closed with [d6bf1cb](https://github.com/dustin10/GeographicalBundle/commit/d6bf1cbcd9aef0c72d2c10183f69f1da59d6278a)
