### ISSUE TITLE
DoctrineODM support?

### ISSUE THREAD

**Issue by laczoka** [dustin10/VichGeographicalBundle#7]
Hi,

without delving too much into the code, I noticed you're using the DBAL to query entities. Do you think it could work with DoctrineODM (MongoDB) as well? 

Thx

Las

**Comment by dustin10** [comment]
It won't work with ODM as it is right now. I have been meaning to add ODM support but have not had time. I will work on this.

**Comment by dustin10** [comment]
I have just commited a first version of a refactoring with ODM support.
